import { ComponentPropsWithoutRef, FC, useEffect, useState } from "react";

type BorderProps = {
  strokeWidth?: number | string;
} & ComponentPropsWithoutRef<"svg">;

export const Border: FC<BorderProps> = ({ strokeWidth = 2, ...props }) => {
  return (
    <div style={{ width: 270, height: 360 }} key={props.key}>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 300 400"
        preserveAspectRatio="none"
        style={{ width: "100%", height: "100%" }}
        {...props}
      >
        <defs>
          <linearGradient id={`gradient-0`} x1="0%" y1="0%" x2="100%" y2="0%">
            <stop
              offset="0%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
            <stop
              offset="50%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={1}
            >
              <animate
                attributeName="offset"
                values="0;1"
                dur="0.8s"
                repeatCount="1"
                fill="freeze"
              />
              <animate
                attributeName="stop-opacity"
                values="0;1;0"
                dur="0.8s"
                repeatCount="1"
                fill="freeze"
              />
            </stop>
            <stop
              offset="100%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
          </linearGradient>
          <linearGradient id={`gradient-1`} x1="0%" y1="0%" x2="100%" y2="0%">
            <stop
              offset="0%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
            <stop
              offset="0"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            >
              <animate
                attributeName="offset"
                values="0;1"
                dur="0.8s"
                repeatCount="1"
                begin="0.2s"
                fill="freeze"
              />
              <animate
                attributeName="stop-opacity"
                values="0;1;0"
                dur="0.8s"
                repeatCount="1"
                begin="0.2s"
                fill="freeze"
              />
            </stop>
            <stop
              offset="100%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
          </linearGradient>
          <linearGradient id={`gradient-2`} x1="0%" y1="0%" x2="100%" y2="0%">
            <stop
              offset="0%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
            <stop
              offset="0"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            >
              <animate
                attributeName="offset"
                values="0;1"
                dur="0.8s"
                repeatCount="1"
                begin="0.4s"
                fill="freeze"
              />
              <animate
                attributeName="stop-opacity"
                values="0;1;0"
                dur="0.8s"
                repeatCount="1"
                begin="0.4s"
                fill="freeze"
              />
            </stop>
            <stop
              offset="100%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
          </linearGradient>
          <linearGradient id={`gradient-3`} x1="0%" y1="0%" x2="100%" y2="0%">
            <stop
              offset="0%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
            <stop
              offset="0"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            >
              <animate
                attributeName="offset"
                values="0;1"
                dur="0.8s"
                repeatCount="1"
                begin="0.6s"
                fill="freeze"
              />
              <animate
                attributeName="stop-opacity"
                values="0;1;0"
                dur="0.8s"
                repeatCount="1"
                begin="0.6s"
                fill="freeze"
              />
            </stop>
            <stop
              offset="100%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
          </linearGradient>
          <linearGradient id={`gradient-4`} x1="0%" y1="0%" x2="100%" y2="0%">
            <stop
              offset="0%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
            <stop
              offset="0"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            >
              <animate
                attributeName="offset"
                values="0;1"
                dur="0.8s"
                repeatCount="1"
                begin="0.8s"
                fill="freeze"
              />
              <animate
                attributeName="stop-opacity"
                values="0;1;0"
                dur="0.8s"
                repeatCount="1"
                begin="0.8s"
                fill="freeze"
              />
            </stop>
            <stop
              offset="100%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
          </linearGradient>

          <linearGradient id={`gradient-v-0`} x1="0%" y1="0%" x2="0%" y2="100%">
            <stop
              offset="0%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
            <stop
              offset="0%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            >
              <animate
                attributeName="offset"
                values="0;1"
                dur="0.8s"
                repeatCount="1"
                begin="0.1s"
                fill="freeze"
              />
              <animate
                attributeName="stop-opacity"
                values="0;1;0"
                dur="0.8s"
                begin="0.1s"
                repeatCount="1"
                fill="freeze"
              />
            </stop>
            <stop
              offset="100%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
          </linearGradient>
          <linearGradient id={`gradient-v-1`} x1="0%" y1="0%" x2="0%" y2="100%">
            <stop
              offset="0%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
            <stop
              offset="0"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            >
              <animate
                attributeName="offset"
                values="0;1"
                dur="0.8s"
                repeatCount="1"
                begin="0.3s"
                fill="freeze"
              />
              <animate
                attributeName="stop-opacity"
                values="0;1;0"
                dur="0.8s"
                begin="0.3s"
                repeatCount="1"
                fill="freeze"
              />
            </stop>
            <stop
              offset="100%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
          </linearGradient>
          <linearGradient id={`gradient-v-2`} x1="0%" y1="0%" x2="0%" y2="100%">
            <stop
              offset="0%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
            <stop
              offset="0"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            >
              <animate
                attributeName="offset"
                values="0;1"
                dur="0.8s"
                repeatCount="1"
                begin="0.5s"
                fill="freeze"
              />
              <animate
                attributeName="stop-opacity"
                values="0;1;0"
                dur="0.8s"
                begin="0.5s"
                repeatCount="1"
                fill="freeze"
              />
            </stop>
            <stop
              offset="100%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
          </linearGradient>
          <linearGradient id={`gradient-v-3`} x1="0%" y1="0%" x2="0%" y2="100%">
            <stop
              offset="0%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
            <stop
              offset="0"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            >
              <animate
                attributeName="offset"
                values="0;1"
                dur="0.8s"
                repeatCount="1"
                begin="0.7s"
                fill="freeze"
              />
              <animate
                attributeName="stop-opacity"
                values="0;1;0"
                dur="0.8s"
                repeatCount="1"
                begin="0.7s"
                fill="freeze"
              />
            </stop>
            <stop
              offset="100%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
          </linearGradient>
          <linearGradient id={`gradient-v-4`} x1="0%" y1="0%" x2="0%" y2="100%">
            <stop
              offset="0%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
            <stop
              offset="0"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            >
              <animate
                attributeName="offset"
                values="0;1"
                dur="0.8s"
                repeatCount="1"
                begin="0.9s"
                fill="freeze"
              />
              <animate
                attributeName="stop-opacity"
                values="0;1;0"
                dur="0.8s"
                repeatCount="1"
                begin="0.9s"
                fill="freeze"
              />
            </stop>
            <stop
              offset="100%"
              stopColor="var(--bls-neutral-minor)"
              stopOpacity={0}
            ></stop>
          </linearGradient>
        </defs>

        <rect
          x="0"
          y="40"
          width="100%"
          height={strokeWidth}
          fill={`url(#gradient-0)`}
        />
        <rect
          x="0"
          y="80"
          width="100%"
          height={strokeWidth}
          fill={`url(#gradient-1)`}
        />
        <rect
          x="0"
          y="120"
          width="100%"
          height={strokeWidth}
          fill={`url(#gradient-2)`}
        />
        <rect
          x="0"
          y="160"
          width="100%"
          height={strokeWidth}
          fill={`url(#gradient-3)`}
        />
        <rect
          x="0"
          y="200"
          width="100%"
          height={strokeWidth}
          fill={`url(#gradient-4)`}
        />

        <rect
          x="40"
          y="0"
          width={strokeWidth}
          height="100%"
          fill={`url(#gradient-v-0)`}
        />
        <rect
          x="80"
          y="0"
          width={strokeWidth}
          height="100%"
          fill={`url(#gradient-v-1)`}
        />
        <rect
          x="120"
          y="0"
          width={strokeWidth}
          height="100%"
          fill={`url(#gradient-v-2)`}
        />
        <rect
          x="160"
          y="0"
          width={strokeWidth}
          height="100%"
          fill={`url(#gradient-v-3)`}
        />
        <rect
          x="200"
          y="0"
          width={strokeWidth}
          height="100%"
          fill={`url(#gradient-v-4)`}
        />
      </svg>
    </div>
  );
};
